#!/bin/bash

WIDTH=19
platform=$(uname)

echo "Testbed"

echo
echo "========  GPU  ========="
if [ -n "$(which nvidia-smi)" ]; then 
    nvidia-smi --query-gpu=name,memory.total --format=csv,noheader | \
        awk -v width=$WIDTH -F ", " '{
            printf "%-*s: %s\n", width, $1, $2
        }'
fi

echo
echo "========  CPU  ========="
if [ "$platform" == "Linux" ]; then
    if [ -n "$(which lscpu)" ]; then
        lscpu | grep -E "Model name|Core\(s\) per socket|Socket\(s\)" | \
            awk -v width=$WIDTH -F ":" '{
                value = $2;
                gsub(/^[[:space:]]+|[[:space:]]+$/, "", value);
                printf "%-*s: %s\n", width, $1, value;
            }'
    fi
elif [ "$platform" == "Darwin" ]; then
    cpu_name=$(sysctl -n machdep.cpu.brand_string)
    cpu_core=$(sysctl -n hw.physicalcpu)
    printf "%-*s: %s\n" $WIDTH "Model name" "$cpu_name"
    printf "%-*s: %s\n" $WIDTH "Core(s)" "$cpu_core"
fi

echo
echo "======== Memory ========"
if [ "$platform" == "Linux" ]; then
    cat /proc/meminfo | grep "MemTotal" | \
        awk -v width=$WIDTH  -F ": +" '{
            printf "%-*s: %s\n", width, "Memory", $2
        }'
elif [ "$platform" == "Darwin" ]; then
    memory_size=$(sysctl -n hw.memsize)
    printf "%-*s: %s B\n" $WIDTH "Memory" "$memory_size"
fi

echo
echo "========  Disk  ========"
if [ "$platform" == "Linux" ]; then
    if [ -n "$(which lsblk)" ]; then
        lsblk -dn -o name,size,rota,type | grep "disk" | \
            awk -v width=$WIDTH '{
                device_name = "/dev/"$1;
                device_size = $2;
                if ($3 == "0") {
                    device_type = "SSD";
                } else {
                    device_type = "HDD";
                }

                disk_list[NR, 0] = device_name;
                disk_list[NR, 1] = device_size;
                disk_list[NR, 2] = device_type;
            }
            END {
                if (NR == 1) {
                    printf "%-*s: Size = %s, Type = %s\n", width, disk_list[NR, 0], disk_list[NR, 1], disk_list[NR, 2];
                } else {
                    for (i = 1; i <= NR; i++) {
                        printf "%-*s: Size = %6s, Type = %s\n", width, disk_list[i, 0], disk_list[i, 1], disk_list[i, 2];
                    }
                }
            }'
    fi
elif [ "$platform" == "Darwin" ]; then
    disk_list=$(diskutil list physical | grep "/dev" | awk '{print $1}' | xargs)
    for disk in ${disk_list[@]}; do
        diskutil info "$disk" | grep "Disk Size" | \
            awk -v width=$WIDTH -v disk=$disk '{
                printf "%-*s: Size = %s %s\n", width, disk, $3, $4
            }'
    done
fi

echo
echo "========   SW   ========"

if [ -e /etc/os-release ]; then
    cat /etc/os-release | grep "PRETTY_NAME" | \
        awk -v width=$WIDTH -F "=" '{
            os_name = $2;
            gsub(/^"|"$/, "", os_name);
            printf "%-*s: %s\n", width, "OS name", os_name;
        }'
fi

if [ -n "$(which uname)" ]; then
    printf "%-*s: %s\n" $WIDTH "Kernel version" "$(uname -sr)"
fi

if [ -n "$(which python3)" ]; then
    printf "%-*s: %s\n" $WIDTH "Python version" "$(python3 --version)"
fi

if [ -n "$(which pip3)" ]; then
    pip3 list | grep "torch " | \
        awk -v width=$WIDTH '{
            printf "%-*s: PyTorch %s\n", width, "PyTorch version", $2
        }'
fi

cuda_version_file="/usr/local/cuda/version.json"
if [ -e "$cuda_version_file" ]; then
    cat $cuda_version_file | grep -A 1 "CUDA SDK" | \
        awk -v width=$WIDTH '{
            if (NR == 2) {
                version = $3;
                gsub(/^"|"$/, "", version);
                printf "%-*s: CUDA %s\n", width, "CUDA version", version;
            }
        }'
fi
