#!/bin/bash

PLATFORM=$(uname)

hw_keys=()
hw_values=()

sw_keys=()
sw_values=()

print_help() {
    echo "Usage:"
    echo
    echo "    -h, --help    Show this help message"
    echo "    --sw          Print Software Information"
    echo "    --hw          Print Hardware Information"
    echo "    -n            Do not print time"
}

print_line() {
    local count=$1
    local delimiter=$2
    echo -n "+"
    for ((i = 0; i < count; i++)); do
        echo -n "$delimiter"
    done
    echo -n "+"
    echo
}

formatted_size() {
    local size=$1

    local unit=${2:-g}
    local base=
    local unit_str=
    if [ "$unit" == 'k' ]; then
        base=1024
        unit_str="KB"
    elif [ "$unit" == 'm' ]; then
        base=$((1024 * 1024))
        unit_str="MB"
    elif [ "$unit" == 'g' ]; then
        base=$((1024 * 1024 * 1024))
        unit_str="GB"
    fi

    local formatted_size=
    if [ -n "$(which bc)" ]; then
        formatted_size=$(echo "scale=1; ${size} / ${base}" | bc)
    else
        formatted_size=$((size  / ${base}))
    fi
    echo "${formatted_size} ${unit_str}"
}

hwstats() {
    hw_keys+=("")
    hw_values+=("GPU")
    if [ -n "$(which nvidia-smi)" ]; then 
        local output=$(nvidia-smi --query-gpu=name,memory.total --format=csv,noheader | awk -F ", " '{printf "%s:%s\n", $1, $2}')
        while IFS=':' read gpu_name gpu_memory; do
            hw_keys+=("$gpu_name")
            hw_values+=("$gpu_memory")
        done <<< "$output"
    else
        hw_keys+=("GPU")
        hw_values+=("Not available")
    fi

    hw_keys+=("")
    hw_values+=("CPU")
    if [ "$PLATFORM" == "Linux" ]; then
        if [ -n "$(which lscpu)" ]; then
            local output=$(lscpu | grep -E "Model name|Core\(s\) per socket|Socket\(s\)" | \
                awk -F ":" '{
                    value = $2;
                    gsub(/^[[:space:]]+|[[:space:]]+$/, "", value);
                    printf "%s:%s\n", $1, value;
                }')
            while IFS=':' read name value; do
                hw_keys+=("$name")
                hw_values+=("$value")
            done <<< "$output"
        fi
    elif [ "$PLATFORM" == "Darwin" ]; then
        local cpu_name=$(sysctl -n machdep.cpu.brand_string)
        local cpu_core=$(sysctl -n hw.physicalcpu)

        local key=("Model name" "Core(s)")
        local value=("$cpu_name" "$cpu_core")

        hw_keys+=("${key[@]}")
        hw_values+=("${value[@]}")
    fi

    hw_keys+=("")
    hw_values+=("Memory")
    hw_keys+=("Memory size")
    local formatted_memory_size=
    if [ "$PLATFORM" == "Linux" ]; then
        # KB
        local memory_size=$(cat /proc/meminfo | grep "MemTotal" | awk -F ": +" '{print $2}')
        formatted_memory_size=$(formatted_size $($memory_size * 1024) "g")
    elif [ "$PLATFORM" == "Darwin" ]; then
        # B
        local memory_size=$(sysctl -n hw.memsize)
        formatted_memory_size=$(formatted_size ${memory_size} "g")
    fi
    hw_values+=("$formatted_memory_size")

    hw_keys+=("")
    hw_values+=("Disk")
    if [ "$PLATFORM" == "Linux" ]; then
        if [ -n "$(which lsblk)" ]; then
            local output=$(lsblk -dn -o name,size,rota,type | grep "disk" | \
                awk '{
                    device_name = "/dev/"$1;
                    device_size = $2;
                    if ($3 == "0") {
                        device_type = "SSD";
                    } else {
                        device_type = "HDD";
                    }

                    disk_list[NR, 0] = device_name;
                    disk_list[NR, 1] = device_size;
                    disk_list[NR, 2] = device_type;
                }
                END {
                    if (NR == 1) {
                        printf "%s:%s:%s\n", disk_list[NR, 0], disk_list[NR, 1], disk_list[NR, 2]
                    } else {
                        for (i = 1; i <= NR; i++) {
                            printf "%s:%6s:%s\n", disk_list[i, 0], disk_list[i, 1], disk_list[i, 2]
                        }
                    }
                }')
            while IFS=':' read device_name device_size device_type; do
                hw_keys+=("$device_name")
                hw_values+=("Size = $device_size, Type = $device_type")
            done <<< "$output"
        fi
    elif [ "$PLATFORM" == "Darwin" ]; then
        local disk_list=$(diskutil list physical | grep "/dev" | awk '{print $1}' | xargs)
        for disk in ${disk_list[@]}; do
            local disk_size=$(diskutil info "$disk" | grep "Disk Size" | awk '{print $3, $4}')
            hw_keys+=("$disk")
            hw_values+=("Size = $disk_size")
        done
    fi
}

swstats() {
    if [ "$PLATFORM" == "Linux" ]; then
        if [ -e /etc/os-release ]; then
            local os_name=$(cat /etc/os-release | grep "PRETTY_NAME" | \
                awk -F "=" '{
                    os_name = $2;
                    gsub(/^"|"$/, "", os_name);
                    print os_name
                }')
            sw_keys+=("OS name")
            sw_values+=("$os_name")
        fi
    elif [ "$PLATFORM" == "Darwin" ]; then
        if [ -n "$(which sw_vers)" ]; then
            sw_keys+=("OS name")
            sw_values+=("$(sw_vers -productName) $(sw_vers -productVersion)")
        fi
    fi

    if [ -n "$(which uname)" ]; then
        sw_keys+=("Kernel version")
        sw_values+=("$(uname -sr)")
    fi

    sw_keys+=("")
    sw_values+=("")
    if [ -n "$(which python3)" ]; then
        sw_keys+=("Python version")
        sw_values+=("$(python3 --version)")
    fi

    if [ -n "$(which pip3)" ]; then
        local output=$(pip3 list | grep -E "scikit-learn|torch |tensorflow-cpu|tensorflow |nvidia-nccl" | \
            awk '{
                package_name = $1;
                version = $2;
                if (package_name == "scikit-learn") {
                    formal_name = "scikit-learn";
                } else if (package_name == "torch") {
                    formal_name = "PyTorch";
                } else if (package_name == "tensorflow-cpu" || package_name == "tensorflow") {
                    formal_name = "TensorFlow";
                } else {
                    formal_name = "NCCL";
                }
                printf "%s:%s:%s\n", formal_name, package_name, version
            }')

        while IFS=':' read formal_name package_name version; do
            sw_keys+=("$formal_name version")
            sw_values+=("$package_name $version")
        done <<< "$output"
                
    fi

    local cuda_version_file="/usr/local/cuda/version.json"
    if [ -e "$cuda_version_file" ]; then
        local cuda_version=$(cat $cuda_version_file | grep -A 1 "CUDA SDK" | \
            awk '{
                if (NR == 2) {
                    version = $3;
                    gsub(/^"|"$/, "", version);
                    print version
                }
            }')
        sw_keys+=("CUDA version")
        sw_values+=("CUDA $cuda_version")
    fi

    sw_keys+=("")
    sw_values+=("")
    if [ -n "$(which gcc)" ]; then
        local gcc_version=
        if [ "$PLATFORM" == "Linux" ]; then
            gcc_version=$(gcc -dumpfullversion)
        elif [ "$PLATFORM" == "Darwin" ]; then
            gcc_version=$(gcc -dumpversion)
        fi
        if [ -n "$gcc_version" ]; then
            sw_keys+=("GCC version")
            sw_values+=("GCC $gcc_version")
        fi
    fi

    if [ -n "$(which make)" ]; then
        local make_version=$(make --version | awk '{if (NR == 1) print $0}')
        sw_keys+=("Make version")
        sw_values+=("$make_version")
    fi

    if [ -n "$(which cmake)" ]; then
        local cmake_version=$(cmake --version | awk '{if (NR == 1) print $3}')
        sw_keys+=("CMake version")
        sw_values+=("CMake $cmake_version")
    fi
}

start=$(date +%s)
print_hw=0
print_sw=0
print_time=1

if [ $# -eq 0 ]; then
    print_hw=1
    print_sw=1
elif [ $# -eq 1 -a $1 == '-n' ]; then
    print_hw=1
    print_sw=1
    print_time=0
else
    while [[ $# -ne 0 ]]; do
        case "$1" in
        -h | --help)
            print_help
            exit
            ;;  
        --hw)
            print_hw=1
            shift
            ;;
        --sw)
            print_sw=1
            shift
            ;;
        -n)
            print_time=0
            shift
            ;;
        *)
            echo "Unknown options: $1"
            exit
            ;;
        esac
    done
fi

key_max_len=0
value_max_len=0
if [ $print_hw == 1 ]; then
    hwstats
    for i in "${!hw_keys[@]}"; do
        key="${hw_keys[$i]}"
        if [ $key_max_len -lt ${#key} ]; then
            key_max_len=${#key}
        fi

        value="${hw_values[$i]}"
        if [ $value_max_len -lt ${#value} ]; then
            value_max_len=${#value}
        fi
    done
fi
if [ $print_sw == 1 ]; then
    swstats
    for i in "${!sw_keys[@]}"; do
        key="${sw_keys[$i]}"
        if [ $key_max_len -lt ${#key} ]; then
            key_max_len=${#key}
        fi

        value="${sw_values[$i]}"
        if [ $value_max_len -lt ${#value} ]; then
            value_max_len=${#value}
        fi
    done
fi

key_width=$((key_max_len + 1))

terminal_width=$(stty size | awk '{print $2}')
line_width=$((1 + key_width + 2 + value_max_len + 1))
if [ $terminal_width -lt $line_width ]; then
    line_width=$terminal_width
fi


calc_width() {
    local text="$1"
    local line_width=$2

    local text_len=${#text}
    local half_width=$(((line_width - text_len) / 2))
    local left_width=$((half_width + text_len))
    local right_width=$((line_width - half_width - text_len))
    echo "$left_width $right_width"
}

echo "Testbed"
echo
if [ $print_hw == 1 ]; then
    for i in "${!hw_keys[@]}"; do
        if [ -z "${hw_keys[$i]}" ]; then
            text="${hw_values[$i]}"
            widths=($(calc_width "$text" $line_width))
            left_width=${widths[0]}
            right_width=${widths[1]}

            print_line $line_width "-"
            printf "|%*s%*s|\n" $left_width "$text" $right_width ""
            print_line $line_width "-"
        else
            printf "| %-*s: %-*s |\n" $key_width "${hw_keys[$i]}" $value_max_len "${hw_values[$i]}"
        fi
    done
    print_line $line_width "-"
fi

if [ $print_sw == 1 ]; then
    text="SW"
    widths=($(calc_width "$text" $line_width))
    left_width=${widths[0]}
    right_width=${widths[1]}

    printf "|%*s%*s|\n" $left_width "$text" $right_width ""
    print_line $line_width "-"
    
    for i in "${!sw_keys[@]}"; do
        if [ -z "${sw_keys[$i]}" ]; then
            print_line $line_width "-"
        else
            printf "| %-*s: %-*s |\n" $key_width "${sw_keys[$i]}" $value_max_len "${sw_values[$i]}"
        fi
    done

    print_line $line_width "-"
fi

if [ $print_time == 1 ]; then 
    end=$(date +%s)
    echo
    printf "  %-*s: %s s\n" $key_width "Elasped time" "$((end - start))"
fi
