#!/bin/bash

WIDTH=19

echo "Testbed"

echo
echo "========  GPU  ========="
if [ -n "$(which nvidia-smi)" ]; then 
    nvidia-smi --query-gpu=name,memory.total --format=csv,noheader | \
        awk -v width=$WIDTH -F ", " '{
            printf "%-*s: %s\n", width, $1, $2
        }'
fi

echo
echo "========  CPU  ========="
lscpu | grep -E "Model name|Core\(s\) per socket|Socket\(s\)" | \
    awk -v width=$WIDTH -F ":" '{
        value = $2;
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", value);
        printf "%-*s: %s\n", width, $1, value;
    }'

echo
echo "======== Memory ========"
cat /proc/meminfo | grep "MemTotal" | \
    awk -v width=$WIDTH  -F ": +" '{
        printf "%-*s: %s\n", width, "Memory", $2
    }'

echo
echo "========  Disk  ========"
lsblk -dn -o name,size,rota,type | grep "disk" | \
    awk -v width=$WIDTH '{
        device_name = "/dev/"$1;
        device_size = $2;
        if ($3 == "0") {
            device_type = "SSD";
        } else {
            device_type = "HDD";
        }

        disk_list[NR, 0] = device_name;
        disk_list[NR, 1] = device_size;
        disk_list[NR, 2] = device_type;
    }
    END {
        if (NR == 1) {
            printf "%-*s: Size = %s, Type = %s\n", width, disk_list[NR, 0], disk_list[NR, 1], disk_list[NR, 2];
        } else {
            for (i = 1; i <= NR; i++) {
                printf "%-*s: Size = %6s, Type = %s\n", width, disk_list[i, 0], disk_list[i, 1], disk_list[i, 2];
            }
        }
    }'
