#!/bin/bash

WIDTH=19

echo "Testbed"

echo
echo "========  GPU  ========="
if [ -n "$(which nvidia-smi)" ]; then 
    nvidia-smi --query-gpu=name,memory.total --format=csv,noheader | \
        awk -v width=$WIDTH -F ", " '{
            printf "%-*s: %s\n", width, $1, $2
        }'
fi

echo
echo "========  CPU  ========="
lscpu | grep -E "Model name|Core\(s\) per socket|Socket\(s\)" | \
    awk -v width=$WIDTH -F ":" '{
        value = $2;
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", value);
        printf "%-*s: %s\n", width, $1, value;
    }'

echo
echo "======== Memory ========"
cat /proc/meminfo | grep "MemTotal" | \
    awk -v width=$WIDTH  -F ": +" '{
        printf "%-*s: %s\n", width, "Memory", $2
    }'

echo
echo "========  Disk  ========"
lsblk -dn -o name,size,rota,type | grep -i 'disk'  | \
    awk -v width=$WIDTH '{
        if ($3 == "0") {
            device_type = "SSD"
        } else {
            device_type = "HDD"
        }
        device_name = "/dev/"$1
        printf "%-*s: Size = %6s, Type = %s\n", width, device_name, $2, device_type
    }'
